name: dri_main
description: DRI Main mobile application bootstrap
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  go_router: ^14.1.0

  # State management (placeholder - decide later: riverpod / bloc)
  provider: ^6.0.5

  # UI helpers
  google_fonts: ^6.2.1

  # For future backend integration (to be added later)
  # supabase_flutter: ^2.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
  generate: true

# Localization configuration (Flutter's gen-l10n will pick up arb files under lib/l10n)